version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: luis
      MYSQL_PASSWORD: 1234
    depends_on:
      - mysql
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: luis
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
